USE ROLE SYSADMIN;

CREATE DATABASE FORECASTING_DEMO;
USE DATABASE FORECASTING_DEMO;

CREATE SCHEMA INGEST;
USE SCHEMA INGEST;

CREATE OR REPLACE WAREHOUSE
    WH_INGEST
WITH
    WAREHOUSE_SIZE='X-LARGE'
    AUTO_RESUME = TRUE
    AUTO_SUSPEND = 30
;
