USE DATABASE REAL_TIME_DEMO;
USE SCHEMA BICING;

CREATE OR REPLACE VIEW
    V_BROKEN_DOCKERS
AS
WITH
m_stations AS (
    SELECT
        STATION_ID,
        CAPACITY AS TOTAL_DOCKS,
        STATION_NAME,
        ADDRESS,
        LAT, LON
    FROM M_BICING_STATIONS
),

current_ AS (
    SELECT
        STATION_ID,
        NUM_BIKES_AVAILABLE + NUM_DOCKS_AVAILABLE AS TOTAL_USABLE_DOCKS
    FROM F_LAST_UPDATED_STATUS
),

final AS (
    SELECT
        mm.STATION_ID, mm.STATION_NAME, mm.ADDRESS, mm.LAT, mm.LON,
        mm.TOTAL_DOCKS - cc.TOTAL_USABLE_DOCKS AS BROKEN_DOCKS

    FROM m_stations mm
    LEFT JOIN current_ cc ON
        mm.STATION_ID = cc.STATION_ID
    WHERE
        cc.TOTAL_USABLE_DOCKS < mm.TOTAL_DOCKS
    ORDER BY BROKEN_DOCKS DESC

)

SELECT * FROM final;
